MIN_NIVEL = 1
MAX_NIVEL = 100
NIVEL_MEGAEV = 'no cacho'  # TODO: cachar ESPERA NO PARECE QUE NO VA

MIN_EXPERIENCIA = 0
MAX_EXPERIENCIA = 100
MIN_AUMENTO_ENTRENAMIENTO = 20  # TODO: REBALANCEAR
MAX_AUMENTO_ENTRENAMIENTO = 50  # TODO: REBALANCEAR
MIN_AUMENTO_EXPERIENCIA = 50  # TODO: REBALANCEAR
MAX_AUMENTO_EXPERIENCIA = 80  # TODO: REBALANCEAR


MIN_VIDA = 1
MAX_VIDA = 255
MIN_ATAQUE = 5
MAX_ATAQUE = 190
MIN_DEFENSA = 5
MAX_DEFENSA = 250
MIN_VELOCIDAD = 5
MAX_VELOCIDAD = 200
PONDERACIONES_LUCHA = (0.2, 0.3, 0.15, 0.15, 0.2, 40)
AUMENTAR_ATAQUE_FUEGO = 38
AUMENTAR_VIDA_PLANTA = 52
AUMENTAR_VELOCIDAD_AGUA = 40